<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPmgx90k\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPmgx90k/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPmgx90k.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPmgx90k\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPmgx90k\appProdProjectContainer([
    'container.build_hash' => 'Pmgx90k',
    'container.build_id' => '79366f27',
    'container.build_time' => 1610929913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPmgx90k');
